### PR TITLE
Update IPerl to work with the new Jupyterlab

### PR DESCRIPTION
**Pull request by Tmarinus**
I take no credit in the code. @dlukes wrote the code on a fork. I am only adding this pull request in the hope more people will be able to see the fix.

I manually applied the patch and it fixes the jupyterlab issue.

### CODE REVIEW

**Comment by dlukes** [comment]
Cool! Happy to see someone else found this useful :)

**Comment by vyuh** [comment]
iperl notebook does not run with Jupyter Notebook 6.2.0 without this patch. Someone please review its backward compatibility and add these changes to CPAN Devel::IPerl.

**Comment by zmughal** [comment]
Thank you @Tmarinus, @dlukes, and @vyuh. Sorry it took me a while to get to this.

I have tested this along with #101 and can confirm it works with both the JupyterLab and classic Jupyter Notebook interfaces (and the console).

I will be doing a release later today.

**Comment by zmughal** [comment]
[Devel-IPerl-0.010](https://metacpan.org/release/ZMUGHAL/Devel-IPerl-0.010) is now on CPAN!

**Pull request merged**
