### PR TITLE
Fix TODO to make ZMQ.pm more robust

### PR DESCRIPTION
**Pull request by thomasjm**
Context: I'm working on a new kind of Jupyter client and I want to support IPerl. It was crashing on multiple ZMQ identities per the TODO in the code.

### CODE REVIEW

**Comment by zmughal** [comment]
Thanks for this! Ignore the failing Travis-CI build check. I've fixed that just now on another branch  (#60).

The reason I had not implemented this item yet is because I did not see when these messages from multiple ZMQ identities would come up. Do you have an example that I can run to test a Jupyter configuration that uses this feature? I want to make sure there is an integration test that I can use to make sure it works properly in the future.

What's the project you're working on, if you don't mind me asking? I'd love to add it to the documentation if it is publicly available.

**Comment by thomasjm** [comment]
I don't have a way to make the multiple identities thing happen with Jupyter. It happened to me using some Haskell ZMQ code derived from IHaskell, which I'm using on my project. For some reason it results in an extra ZMQ message being sent, I'm not sure why. Most kernels I've seen just read until the delimiter.

The project is a new kind of interactive notebook called Literate Markdown. It's in early beta now but I'm hoping to release more broadly soon. Would appreciate any feedback if you're interested: https://literatemarkdown.com/standalone

**Comment by zmughal** [comment]
Ah, I see! I'll have to put together a simple Jupyter ZMQ client then. It's something I've put off for quite a while anyway, so now would be as good a time as any.

Literate Markdown looks neat! Based on Pandoc, I assume? I really like that nested code idea.

It would be nice to have a small cursor that can indicate where the user is typing in the rendered document especially as documents get larger. Kind of like a forward/inverse search for LaTeX.

**Comment by zmughal** [comment]
Also, do you mind squashing these commits and adding a bit more description in the commit message? 

I can do it if you'd like, but I'd like to give you an opportunity to do it before I merge this in. There's no rush.

**Comment by thomasjm** [comment]
Okay, just squashed and changed the commit message.

I noticed you made a LiterateMarkdown account, so I created a container for you -- you can find it linked from your profile page. Feel free to play around!

**Comment by thomasjm** [comment]
Thanks for the suggestion about a cursor in the rendered document. I'm thinking long-term the direction I want to go is to make the HTML itself editable, so you can hide the markdown view and just work on the rendered document directly.

**Comment by zmughal** [comment]
Sorry for leaving this open for so long! I'm close to having tests for this, but might as well get this in first!

**Pull request merged**
